name: RDT_sysid
channels:
  - conda-forge
  - defaults
dependencies:
  - blas=1.0=openblas  # Replace MKL with OpenBLAS
  - bottleneck
  - brotli
  - brotli-bin
  - bzip2
  - c-ares
  - ca-certificates
  - contourpy
  - cycler
  - expat
  - fontconfig
  - fonttools
  - freetype
  - glib
  - gst-plugins-base
  - gstreamer
  - icu
  - jpeg
  - kiwisolver
  - lcms2
  - lerc
  - libcurl
  - libdeflate
  - libedit
  - libev
  - libffi
  - libiconv
  - libnghttp2
  - libpng
  - libprotobuf
  - libssh2
  - libtiff
  - libuuid
  - libwebp-base
  - libxcb  # Keeping this in case it's needed, can remove if errors persist
  - libxml2
  - lz4-c
  - matplotlib
  - matplotlib-base
  - ncurses
  - numexpr
  - numpy
  - numpy-base
  - openjpeg
  - openssl
  - packaging
  - pandas
  - pcre2
  - pillow
  - pip
  - ply
  - pyparsing
  - pyqt
  - pyqt5-sip
  - python=3.10
  - python-dateutil
  - python-tzdata
  - pytz
  - readline
  - scipy
  - setuptools
  - sip
  - six
  - sqlite
  - tk
  - tomli
  - tornado
  - tzdata
  - unicodedata2
  - wheel
  - xz
  - zlib
  - zstd
  - pip:
      - absl-py
      - asttokens
      - cloudpickle
      - decorator
      - etils
      - exceptiongroup
      - executing
      - farama-notifications
      - fsspec
      - glfw
      - gym
      - gym-notices
      - gymnasium
      - imageio
      - importlib-resources
      - ipython
      - jax
      - jaxlib
      - jedi
      - llvmlite
      - matplotlib-inline
      - mediapy
      - ml-dtypes
      - mujoco
      - mujoco-mjx
      - mujoco-sysid
      - numba
      - numpy-quaternion
      - opt-einsum
      - parso
      - pexpect
      - prompt-toolkit
      - ptyprocess
      - pure-eval
      - pygments
      - pyopengl
      - stack-data
      - traitlets
      - trimesh
      - typing-extensions
      - wcwidth
      - zipp